name: Deploy to Production

on:
  push:
    branches:
      - main # Thay thế bằng tên nhánh mà bạn muốn trigger CI/CD (ví dụ: main, master)

jobs:
  deploy:
    runs-on: self-hosted # Sử dụng runner tự host

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        run: |
          sudo apt install php-curl php-gd php-mbstring php-xml php-xmlrpc php-soap php-intl php-zip
          sudo apt-get install php8.3 php8.3-fpm
          sudo systemctl restart php8.3-fpm

      - name: Install WordPress CLI
        run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          chmod +x wp-cli.phar
          sudo mv wp-cli.phar /usr/local/bin/wp

      - name: Deploy WordPress
        run: |
          cd /var/www/html
          sudo git pull origin main  
          sudo git checkout main  
          sudo chown -R www-data:www-data /var/www/html/WP-and-WOO  
          sudo service nginx reload
